name = "PAPA"
uuid = "52669280-9ad1-11e9-1f56-2da0aee6d022"
authors = ["Luke C. Govia"]
version = "0.1.0"

[deps]
LeastSquaresOptim = "0fc2ff8b-aaa3-5acd-a817-1944a5e08891"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LeastSquaresOptim = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
